import type { Conversation, Message } from "@/types/message";
import type { User } from "@/types/user";

// // FAKE DATA: Current user
export const currentUser: User = {
  id: "user_me",
  name: "Cường",
  avatar: "https://i.pravatar.cc/150?img=1",
  email: "me@example.com",
  isOnline: true,
};

// // FAKE DATA: Users (participants in conversations)
const users: Record<string, User> = {
  user_1: {
    id: "user_1",
    name: "Bun",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "cuong@example.com",
    isOnline: true,
  },
  user_2: {
    id: "user_2",
    name: "Đông Thi",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "minhanh@example.com",
    isOnline: true,
  },
  user_3: {
    id: "user_3",
    name: "Tuấn",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "tuan@example.com",
    isOnline: false,
    lastSeen: new Date(Date.now() - 3600000).toISOString(),
  },
  user_4: {
    id: "user_4",
    name: "Hương",
    avatar: "https://i.pravatar.cc/150?img=9",
    email: "huong@example.com",
    isOnline: true,
  },
  user_5: {
    id: "user_5",
    name: "Đức",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "duc@example.com",
    isOnline: false,
    lastSeen: new Date(Date.now() - 18000000).toISOString(),
  },
  user_6: {
    id: "user_6",
    name: "Phương",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "phuong@example.com",
    isOnline: false,
    lastSeen: new Date(Date.now() - 86400000).toISOString(),
  },
  user_7: {
    id: "user_7",
    name: "Nam",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "nam@example.com",
    isOnline: false,
    lastSeen: new Date(Date.now() - 86400000).toISOString(),
  },
  user_8: {
    id: "user_8",
    name: "Linh",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "linh@example.com",
    isOnline: false,
    lastSeen: new Date(Date.now() - 172800000).toISOString(),
  },
};

// FAKE DATA: Message
export const messagesData: Record<string, Message[]> = {
  conv_1: [
    {
      id: "msg_1_1",
      conversationId: "conv_1",
      senderId: "user_1",
      text: "Ê bro",
      sender: "them",
      timestamp: "10:30 AM",
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_1_2",
      conversationId: "conv_1",
      senderId: "user_1",
      text: "Sao rồi?",
      sender: "them",
      timestamp: "10:30 AM",
      createdAt: new Date(Date.now() - 3540000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_1_3",
      conversationId: "conv_1",
      senderId: "user_me",
      text: "Ổn á, mày sao?",
      sender: "me",
      timestamp: "10:32 AM",
      createdAt: new Date(Date.now() - 3480000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_1_4",
      conversationId: "conv_1",
      senderId: "user_1",
      text: "Ổn nè, nay ăn gì mày",
      sender: "them",
      timestamp: "10:33 AM",
      createdAt: new Date(Date.now() - 3420000).toISOString(),
      isRead: false,
      status: "sent",
      type: "text",
    },
    {
      id: "msg_1_5",
      conversationId: "conv_1",
      senderId: "user_me",
      text: "Chưa biết, mày muốn ăn gì?",
      sender: "me",
      timestamp: "10:35 AM",
      createdAt: new Date(Date.now() - 3300000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_1_6",
      conversationId: "conv_1",
      senderId: "user_1",
      text: "Lẩu đi bro",
      sender: "them",
      timestamp: "10:35 AM",
      createdAt: new Date(Date.now() - 60000).toISOString(),
      isRead: false,
      status: "sent",
      type: "text",
    },
  ],
  conv_2: [
    {
      id: "msg_2_1",
      conversationId: "conv_2",
      senderId: "user_2",
      text: "Em muốn gặp anh",
      sender: "them",
      timestamp: "9:00 AM",
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_2_2",
      conversationId: "conv_2",
      senderId: "user_me",
      text: "9 giờ đêm nay tại phòng anh nhé",
      sender: "me",
      timestamp: "9:05 AM",
      createdAt: new Date(Date.now() - 7080000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_2_3",
      conversationId: "conv_2",
      senderId: "user_2",
      text: "Oke anh, hẹn gặp anh",
      sender: "them",
      timestamp: "9:06 AM",
      createdAt: new Date(Date.now() - 120000).toISOString(),
      isRead: false,
      status: "sent",
      type: "text",
    },
  ],
  conv_3: [
    {
      id: "msg_3_1",
      conversationId: "conv_3",
      senderId: "user_3",
      text: "Bạn ơi có file tài liệu không?",
      sender: "them",
      timestamp: "Yesterday",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_3_2",
      conversationId: "conv_3",
      senderId: "user_me",
      text: "Có nè, để mình gửi cho",
      sender: "me",
      timestamp: "Yesterday",
      createdAt: new Date(Date.now() - 86340000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    {
      id: "msg_3_3",
      conversationId: "conv_3",
      senderId: "user_me",
      text: "Đã gửi một file",
      sender: "me",
      timestamp: "Yesterday",
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      isRead: true,
      status: "read",
      type: "file",
    },
  ],
};

// // FAKE DATA: Conversations list
export const conversationsData: Conversation[] = [
  {
    id: "conv_1",
    participantId: "user_1",
    participant: users.user_1,
    lastMessage: messagesData.conv_1[messagesData.conv_1.length - 1],
    unreadCount: 3,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 2592000000).toISOString(),
    updatedAt: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: "conv_2",
    participantId: "user_2",
    participant: users.user_2,
    lastMessage: messagesData.conv_2[messagesData.conv_2.length - 1],
    unreadCount: 1,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 1296000000).toISOString(),
    updatedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "conv_3",
    participantId: "user_3",
    participant: users.user_3,
    lastMessage: messagesData.conv_3[messagesData.conv_3.length - 1],
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "conv_4",
    participantId: "user_4",
    participant: users.user_4,
    lastMessage: {
      id: "msg_4_last",
      conversationId: "conv_4",
      senderId: "user_4",
      text: "Haha đúng rồi đó",
      sender: "them",
      timestamp: "3h",
      createdAt: new Date(Date.now() - 10800000).toISOString(),
      isRead: false,
      status: "sent",
      type: "text",
    },
    unreadCount: 5,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "conv_5",
    participantId: "user_5",
    participant: users.user_5,
    lastMessage: {
      id: "msg_5_last",
      conversationId: "conv_5",
      senderId: "user_5",
      text: "Thanks bạn nha!",
      sender: "them",
      timestamp: "5h",
      createdAt: new Date(Date.now() - 18000000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: "conv_6",
    participantId: "user_6",
    participant: users.user_6,
    lastMessage: {
      id: "msg_6_last",
      conversationId: "conv_6",
      senderId: "user_6",
      text: "Chiều nay có rảnh không?",
      sender: "them",
      timestamp: "Yesterday",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "conv_7",
    participantId: "user_7",
    participant: users.user_7,
    lastMessage: {
      id: "msg_7_last",
      conversationId: "conv_7",
      senderId: "user_7",
      text: "Xem bóng đá không bro?",
      sender: "them",
      timestamp: "Yesterday",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "conv_8",
    participantId: "user_8",
    participant: users.user_8,
    lastMessage: {
      id: "msg_8_last",
      conversationId: "conv_8",
      senderId: "user_8",
      text: "Ok nha, cảm ơn bạn nhiều",
      sender: "them",
      timestamp: "2 days ago",
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      isRead: true,
      status: "read",
      type: "text",
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

// FAKE DATA: Potential Friends (users not yet friends with)
export const potentialFriends: User[] = [
  {
    id: "user_9",
    name: "Mai",
    avatar: "https://i.pravatar.cc/150?img=26",
    email: "mai@example.com",
    isOnline: true,
  },
  {
    id: "user_10",
    name: "Khoa",
    avatar: "https://i.pravatar.cc/150?img=13",
    email: "khoa@example.com",
    isOnline: false,
  },
  {
    id: "user_11",
    name: "Thảo",
    avatar: "https://i.pravatar.cc/150?img=47",
    email: "thao@example.com",
    isOnline: true,
  },
  {
    id: "user_12",
    name: "Duy",
    avatar: "https://i.pravatar.cc/150?img=11",
    email: "duy@example.com",
    isOnline: false,
  },
  {
    id: "user_13",
    name: "Lan",
    avatar: "https://i.pravatar.cc/150?img=32",
    email: "lan@example.com",
    isOnline: true,
  },
  {
    id: "user_14",
    name: "Hoàng",
    avatar: "https://i.pravatar.cc/150?img=52",
    email: "hoang@example.com",
    isOnline: false,
  },
  {
    id: "user_15",
    name: "Nga",
    avatar: "https://i.pravatar.cc/150?img=23",
    email: "nga@example.com",
    isOnline: true,
  },
  {
    id: "user_16",
    name: "Minh",
    avatar: "https://i.pravatar.cc/150?img=60",
    email: "minh@example.com",
    isOnline: false,
  },
];
